spring:
    application:
        name: ecomerce

    datasource:
        url: jdbc:mysql://localhost:3307/app_db
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.MySQL8Dialect